<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    "catalogrule/rule_condition_combine" => "Magento\CatalogRule\Model\Rule\Condition\Combine",
    "catalogrule/rule_condition_product" => "Magento\CatalogRule\Model\Rule\Condition\Product",
    "catalogrule/rule_product_price" => "Magento\CatalogRule\Model\Rule\Product\Price",
    "catalogrule/rule_action_collection" => "Magento\CatalogRule\Model\Rule\Action\Collection",
    "catalogrule/rule_action_product" => "Magento\CatalogRule\Model\Rule\Action\Product",
    "salesrule/rule_condition_combine" => "Magento\SalesRule\Model\Rule\Condition\Combine",
    "salesrule/rule_condition_address" => "Magento\SalesRule\Model\Rule\Condition\Address",
    "salesrule/rule_condition_product" => "Magento\SalesRule\Model\Rule\Condition\Product",
    "salesrule/rule_condition_product_combine" => "Magento\SalesRule\Model\Rule\Condition\Product\Combine",
    "salesrule/rule_condition_product_found" => "Magento\SalesRule\Model\Rule\Condition\Product\Found",
    "salesrule/rule_condition_product_subselect" => "Magento\SalesRule\Model\Rule\Condition\Product\Subselect",
    "salesrule/rule_action_collection" => "Magento\CatalogRule\Model\Rule\Action\Collection",
    "salesrule/rule_action_product" => "Magento\CatalogRule\Model\Rule\Action\Product",
    "salesrule/rule_product" => "Magento\SalesRule\Model\Rule\Product",
    "salesrule/rule_customer" => "Magento\SalesRule\Model\Rule\Customer",
    "enterprise_targetrule/rule_condition_combine" => "Magento\TargetRule\Model\Rule\Condition\Combine",
    "enterprise_targetrule/rule_condition_product_attributes" => "Magento\TargetRule\Model\Rule\Condition\Product\Attributes",
    "enterprise_targetrule/actions_condition_product_special_price" => "Magento\TargetRule\Model\Actions\Condition\Product\Special\Price",
    "enterprise_targetrule/actions_condition_product_special" => "Magento\TargetRule\Model\Actions\Condition\Product\Special",
    "enterprise_targetrule/actions_condition_product_attributes" => "Magento\TargetRule\Model\Actions\Condition\Product\Attributes",
    "enterprise_targetrule/actions_condition_combine" => "Magento\TargetRule\Model\Actions\Condition\Combine",
    "enterprise_reminder/rule_condition_combine" => "\Magento\Reminder\Model\Rule\Condition\Combine",
    "enterprise_reminder/rule_condition_combine_root" => "\Magento\Reminder\Model\Rule\Condition\Combine\Root",
    "enterprise_reminder/rule_condition_cart" => "\Magento\Reminder\Model\Rule\Condition\Cart",
    "enterprise_reminder/rule_condition_cart_amount" => "\Magento\Reminder\Model\Rule\Condition\Cart\Amount",
    "enterprise_reminder/rule_condition_cart_attributes" => "\Magento\Reminder\Model\Rule\Condition\Cart\Attributes",
    "enterprise_reminder/rule_condition_cart_combine" => "\Magento\Reminder\Model\Rule\Condition\Cart\Combine",
    "enterprise_reminder/rule_condition_cart_couponcode" => "\Magento\Reminder\Model\Rule\Condition\Cart\Couponcode",
    "enterprise_reminder/rule_condition_cart_itemsquantity" => "\Magento\Reminder\Model\Rule\Condition\Cart\Itemsquantity",
    "enterprise_reminder/rule_condition_cart_sku" => "\Magento\Reminder\Model\Rule\Condition\Cart\Sku",
    "enterprise_reminder/rule_condition_cart_storeview" => "\Magento\Reminder\Model\Rule\Condition\Cart\Storeview",
    "enterprise_reminder/rule_condition_cart_subcombine" => "\Magento\Reminder\Model\Rule\Condition\Cart\Subcombine",
    "enterprise_reminder/rule_condition_cart_subselection" => "\Magento\Reminder\Model\Rule\Condition\Cart\Subselection",
    "enterprise_reminder/rule_condition_cart_totalquantity" => "\Magento\Reminder\Model\Rule\Condition\Cart\Totalquantity",
    "enterprise_reminder/rule_condition_cart_virtual" => "\Magento\Reminder\Model\Rule\Condition\Cart\Virtual",
    "enterprise_reminder/rule_condition_wishlist" => "\Magento\Reminder\Model\Rule\Condition\Wishlist",
    "enterprise_reminder/rule_condition_wishlist_attributes" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Attributes",
    "enterprise_reminder/rule_condition_wishlist_combine" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Combine",
    "enterprise_reminder/rule_condition_wishlist_quantity" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Quantity",
    "enterprise_reminder/rule_condition_wishlist_sharing" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Sharing",
    "enterprise_reminder/rule_condition_wishlist_storeview" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Storeview",
    "enterprise_reminder/rule_condition_wishlist_subcombine" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Subcombine",
    "enterprise_reminder/rule_condition_wishlist_subselection" => "\Magento\Reminder\Model\Rule\Condition\Wishlist\Subselection",
    "enterprise_banner/widget_banner" => "Magento\Banner\Block\Widget\Banner",
    "enterprise_catalogevent/widget_lister" => "Magento\CatalogEvent\Block\Widget\Lister",
    "enterprise_checkout/widget_sku" => "Magento\AdvancedCheckout\Block\Widget\Sku",
    "enterprise_cms/widget_node" => "Magento\VersionsCms\Block\Widget\Node",
    "enterprise_giftregistry/search_widget_form" => "Magento\GiftRegistry\Block\Search\Widget\Form",
    "enterprise_wishlist/widget_search" => "Magento\MultipleWishlist\Block\Widget\Search",
    "catalog/product_widget_new" => "Magento\Catalog\Block\Product\Widget\NewWidget",
    "catalog/product_widget_link" => "Magento\Catalog\Block\Product\Widget\Link",
    "catalog/category_widget_link" => "Magento\Catalog\Block\Category\Widget\Link",
    "cms/widget_page_link" => "Magento\Cms\Block\Widget\Page\Link",
    "cms/widget_block" => "Magento\Cms\Block\Widget\Block",
    "reports/product_widget_viewed" => "Magento\Reports\Block\Product\Widget\Viewed",
    "reports/product_widget_compared" => "Magento\Reports\Block\Product\Widget\Compared",
    "sales/widget_guest_form" => "Magento\Sales\Block\Widget\Guest\Form",
    "enterprise_catalogevent/event_lister" => "Magento\CatalogEvent\Block\Event\Lister"
];
