<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'catalogrule/rule_condition_combine' => 'Magento\CatalogRule\Model\Rule\Condition\Combine',
    'adminhtml/catalog_category_helper_pricestep' => 'Magento\Catalog\Block\Adminhtml\Category\Helper\Pricestep',
    'adminhtml/catalog_category_helper_sortby_available' =>
        'Magento\Catalog\Block\Adminhtml\Category\Helper\Sortby\Available',
    'adminhtml/catalog_category_helper_sortby_default' =>
        'Magento\Catalog\Block\Adminhtml\Category\Helper\Sortby\DefaultSortby',
    'adminhtml/catalog_product_helper_form_msrp_enabled' => null,
    'adminhtml/catalog_product_helper_form_msrp_price' => 'Magento\Msrp\Block\Adminhtml\Product\Helper\Form\Type\Price',
    'bundle/product_attribute_source_price_view' => 'Magento\Bundle\Model\Product\Attribute\Source\Price\View',
    'catalog/attribute_backend_customlayoutupdate' => 'Magento\Catalog\Model\Attribute\Backend\Customlayoutupdate',
    'catalog/category' => 'Magento\Catalog\Model\Resource\Category',
    'catalog/category_attribute_backend_image' => 'Magento\Catalog\Model\Category\Attribute\Backend\Image',
    'catalog/category_attribute_backend_sortby' => 'Magento\Catalog\Model\Category\Attribute\Backend\Sortby',
    'catalog/category_attribute_backend_urlkey' => null,
    'catalog/product_attribute_backend_urlkey' => null,
    'catalog/category_attribute_collection' => 'Magento\Catalog\Model\Resource\Category\Attribute\Collection',
    'catalog/category_attribute_source_layout' => 'Magento\Catalog\Model\Category\Attribute\Source\Layout',
    'catalog/category_attribute_source_mode' => 'Magento\Catalog\Model\Category\Attribute\Source\Mode',
    'catalog/category_attribute_source_page' => 'Magento\Catalog\Model\Category\Attribute\Source\Page',
    'catalog/category_attribute_source_sortby' => 'Magento\Catalog\Model\Category\Attribute\Source\Sortby',
    'catalog/category_widget_link' => 'Magento\Catalog\Block\Category\Widget\Link',
    'catalog/entity_product_attribute_design_options_container' =>
        'Magento\Catalog\Model\Entity\Product\Attribute\Design\Options\Container',
    'catalog/product' => 'Magento\Catalog\Model\Resource\Product',
    'catalog/product_attribute_backend_boolean' => 'Magento\Catalog\Model\Product\Attribute\Backend\Boolean',
    'catalog/product_attribute_backend_groupprice' => 'Magento\Catalog\Model\Product\Attribute\Backend\GroupPrice',
    'catalog/product_attribute_backend_media' => 'Magento\Catalog\Model\Product\Attribute\Backend\Media',
    'catalog/product_attribute_backend_msrp' => null,
    'catalog/product_attribute_backend_price' => 'Magento\Catalog\Model\Product\Attribute\Backend\Price',
    'catalog/product_attribute_backend_recurring' => null,
    'catalog/product_attribute_backend_sku' => 'Magento\Catalog\Model\Product\Attribute\Backend\Sku',
    'catalog/product_attribute_backend_startdate' => 'Magento\Catalog\Model\Product\Attribute\Backend\Startdate',
    'catalog/product_attribute_backend_startdate_specialprice' =>
        'Magento\Catalog\Model\Product\Attribute\Backend\Startdate',
    'catalog/product_attribute_backend_tierprice' => 'Magento\Catalog\Model\Product\Attribute\Backend\Tierprice',
    'catalog/product_attribute_collection' => 'Magento\Catalog\Model\Resource\Product\Attribute\Collection',
    'catalog/product_attribute_frontend_image' => 'Magento\Catalog\Model\Product\Attribute\Frontend\Image',
    'catalog/product_attribute_source_countryofmanufacture' =>
        'Magento\Catalog\Model\Product\Attribute\Source\Countryofmanufacture',
    'catalog/product_attribute_source_layout' => 'Magento\Catalog\Model\Product\Attribute\Source\Layout',
    'catalog/product_attribute_source_msrp_type_enabled' => null,
    'catalog/product_attribute_source_msrp_type_price' => 'Magento\Msrp\Model\Product\Attribute\Source\Type\Price',
    'catalog/product_status' => 'Magento\Catalog\Model\Product\Attribute\Source\Status',
    'catalog/product_visibility' => 'Magento\Catalog\Model\Product\Visibility',
    'catalog/product_widget_link' => 'Magento\Catalog\Block\Product\Widget\Link',
    'catalog/product_widget_new' => 'Magento\Catalog\Block\Product\Widget\NewWidget',
    'catalog/resource_eav_attribute' => 'Magento\Catalog\Model\Resource\Eav\Attribute',
    'catalogrule/rule_action_collection' => 'Magento\CatalogRule\Model\Rule\Action\Collection',
    'catalogrule/rule_action_product' => 'Magento\CatalogRule\Model\Rule\Action\Product',
    'catalogrule/rule_condition_product' => 'Magento\CatalogRule\Model\Rule\Condition\Product',
    'catalogrule/rule_product_price' => 'Magento\CatalogRule\Model\Rule\Product\Price',
    'cms/widget_block' => 'Magento\Cms\Block\Widget\Block',
    'cms/widget_page_link' => 'Magento\Cms\Block\Widget\Page\Link',
    'core/design_source_design' => 'Magento\Theme\Model\Theme\Source\Theme',
    'customer/address' => 'Magento\Customer\Model\Resource\Address',
    'customer/address_attribute_collection' => 'Magento\Customer\Model\Resource\Address\Attribute\Collection',
    'customer/attribute' => 'Magento\Customer\Model\Attribute',
    'customer/attribute_backend_data_boolean' => 'Magento\Customer\Model\Attribute\Backend\Data\Boolean',
    'customer/attribute_collection' => 'Magento\Customer\Model\Resource\Attribute\Collection',
    'customer/attribute_data_postcode' => 'Magento\Customer\Model\Attribute\Data\Postcode',
    'customer/customer' => 'Magento\Customer\Model\Resource\Customer',
    'customer/customer_attribute_backend_billing' => 'Magento\Customer\Model\Customer\Attribute\Backend\Billing',
    'customer/customer_attribute_backend_password' => 'Magento\Customer\Model\Customer\Attribute\Backend\Password',
    'customer/customer_attribute_backend_shipping' => 'Magento\Customer\Model\Customer\Attribute\Backend\Shipping',
    'customer/customer_attribute_backend_store' => 'Magento\Customer\Model\Customer\Attribute\Backend\Store',
    'customer/customer_attribute_backend_website' => 'Magento\Customer\Model\Customer\Attribute\Backend\Website',
    'customer/customer_attribute_source_group' => 'Magento\Customer\Model\Customer\Attribute\Source\Group',
    'customer/customer_attribute_source_store' => 'Magento\Customer\Model\Customer\Attribute\Source\Store',
    'customer/customer_attribute_source_website' => 'Magento\Customer\Model\Customer\Attribute\Source\Website',
    'customer/entity_address_attribute_backend_region' =>
        'Magento\Customer\Model\Resource\Address\Attribute\Backend\Region',
    'customer/entity_address_attribute_backend_street' => 'Magento\Eav\Model\Entity\Attribute\Backend\DefaultBackend',
    'customer/entity_address_attribute_source_country' =>
        'Magento\Customer\Model\Resource\Address\Attribute\Source\Country',
    'customer/entity_address_attribute_source_region' =>
        'Magento\Customer\Model\Resource\Address\Attribute\Source\Region',
    'eav/entity_attribute_backend_array' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
    'eav/entity_attribute_backend_datetime' => 'Magento\Eav\Model\Entity\Attribute\Backend\Datetime',
    'eav/entity_attribute_backend_time_created' => 'Magento\Eav\Model\Entity\Attribute\Backend\Time\Created',
    'eav/entity_attribute_backend_time_updated' => 'Magento\Eav\Model\Entity\Attribute\Backend\Time\Updated',
    'eav/entity_attribute_frontend_datetime' => 'Magento\Eav\Model\Entity\Attribute\Frontend\Datetime',
    'eav/entity_attribute_source_boolean' => 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
    'eav/entity_attribute_source_table' => 'Magento\Eav\Model\Entity\Attribute\Source\Table',
    'eav/entity_increment_numeric' => 'Magento\Eav\Model\Entity\Increment\Numeric',
    'giftmessage/adminhtml_product_helper_form_config' =>
        'Magento\GiftMessage\Block\Adminhtml\Product\Helper\Form\Config',
    'reports/product_widget_compared' => 'Magento\Reports\Block\Product\Widget\Compared',
    'reports/product_widget_viewed' => 'Magento\Reports\Block\Product\Widget\Viewed',
    'sales/order' => 'Magento\Sales\Model\Resource\Order',
    'sales/order_creditmemo' => 'Magento\Sales\Model\Resource\Order\Creditmemo',
    'sales/order_invoice' => 'Magento\Sales\Model\Resource\Order\Invoice',
    'sales/order_shipment' => 'Magento\Sales\Model\Resource\Order\Shipment',
    'sales/widget_guest_form' => 'Magento\Sales\Block\Widget\Guest\Form',
    'salesrule/rule_action_collection' => 'Magento\CatalogRule\Model\Rule\Action\Collection',
    'salesrule/rule_action_product' => 'Magento\CatalogRule\Model\Rule\Action\Product',
    'salesrule/rule_condition_address' => 'Magento\SalesRule\Model\Rule\Condition\Address',
    'salesrule/rule_condition_combine' => 'Magento\SalesRule\Model\Rule\Condition\Combine',
    'salesrule/rule_condition_product' => 'Magento\SalesRule\Model\Rule\Condition\Product',
    'salesrule/rule_condition_product_combine' => 'Magento\SalesRule\Model\Rule\Condition\Product\Combine',
    'salesrule/rule_condition_product_found' => 'Magento\SalesRule\Model\Rule\Condition\Product\Found',
    'salesrule/rule_condition_product_subselect' => 'Magento\SalesRule\Model\Rule\Condition\Product\Subselect',
    'salesrule/rule_customer' => 'Magento\SalesRule\Model\Rule\Customer',
    'salesrule/rule_product' => 'Magento\SalesRule\Model\Rule\Product',
    'tax/class_source_product' => 'Magento\Tax\Model\TaxClass\Source\Product'
];
